# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 08:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=52, verbose_name='Symbol')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('unit', models.CharField(choices=[('SZT', 'SZT')], default='SZT', max_length=4, verbose_name='Unit')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created date')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
                ('place_order', models.ManyToManyField(blank=True, null=True, related_name='place_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
