# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-13 15:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20180613_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placeorder',
            name='order_by',
        ),
        migrations.RemoveField(
            model_name='placeorder',
            name='product',
        ),
        migrations.DeleteModel(
            name='PlaceOrder',
        ),
    ]
