# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-14 05:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0003_auto_20180613_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True, verbose_name='Quantity')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_orders', to='product.Product')),
                ('product_order_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_orders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
